# This config file is meant for settings that affect your whole blog
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

livereload: true

title: Learn to Speak the Secret Gibberish Language Game

tagline:  The idiolect of the Gibberish Language

description: Gibberish Umbra brings light from behind the shadow of the Gibberish lexicon.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gibberish.cyou" # the base hostname & protocol for your site, e.g. http://example.com

timezone: America/Los_Angeles

logo: /gibberish-umbra-512-icon.png

email: speak@gibberish.cyou
youtube_username: channel/UCbhzao2COAXoYIULI4N5acQ
instagram_username: gibberish.umbra
facebook_username: gibberish.umbra
twitter_username: GibberishUmbra
snapchat_username: gibberish.umbra
redcircle_username: 
rss: ""


twitter:
  username: GibberishUmbra
  card: summary

facebook:
  app_id: 609315026396624
  publisher: 113082303650155

social:
  name: Gibberish Umbra
  links:
    - https://twitter.com/GibberishUmbra
    - https://www.facebook.com/gibberish.umbra
    - https://www.instagram.com/gibberish.umbra
    - https://www.youtube.com/channel/UCbhzao2COAXoYIULI4N5acQ

#linkedin_username: chuck-barr-pdx
#github_username: cvk
google_analytics: UA-175444935-1


# added built-ins
author: gibberish.umbra

# add-ins not from jekyll new
copyright: "SP" #Sole Proprietorship
title-logo: /gibberish-umbra-512-icon.png
manifest-json: /manifest.json

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

minima:
  date_format: "%y%j"

header_pages:
  - about.markdown
  - channel/index.markdown
  - podcast/index.markdown
  - written/index.markdown
  - twitter.md
  - social.md
  

# Exclude from processing.
# The following items will not be processed, by default.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - ngrok
